-- Tabla Alumno Fijo (Jerarquía - hereda de Alumno)
CREATE TABLE IF NOT EXISTS pyac.alumnofijo(
    dni INT PRIMARY KEY,
    lun BOOLEAN NOT NULL DEFAULT FALSE,
    mar BOOLEAN NOT NULL DEFAULT FALSE,
    mie BOOLEAN NOT NULL DEFAULT FALSE,
    jue BOOLEAN NOT NULL DEFAULT FALSE,
    vie BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (dni) REFERENCES pyac.alumno(dni)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON pyac.alumnofijo TO pyac_admin;